### ISSUE TITLE
Link to demo broken

### ISSUE THREAD

**Issue by falkenhawk** [CoCreate-app/CoCreate-modal#13]
Hey, just a heads up that the link do a playground/docs in the README is broken, https://cocreate.app/docs/modal leads to 404.

**Comment by MERNBlockchainStar** [comment]
How are you?
Hope your project going well.
Just hope to work in this project. 
If you are interested in me , please let me know

**Comment by frankpagan** [comment]
fix: updated broken link to playground/docs in README

The link to the Modal documentation in the README was leading to a 404. Updated the link to point to the correct URL. Thank you for bringing this to our attention!
